### READ
GET http://localhost:3000/vocabulary/663ddf614f79af2b81fffaf9 HTTP/1.1

### CREATE
POST http://localhost:3000/vocabulary HTTP/1.1
Content-Type: application/json

{
    "englishWord": "Romanisation",
    "englishDescription": "Description",
    "characters": [
        {
            "chinese": "BABY!",
            "roman": ["ping"],
            "yale": ["ping1", "ping3"],
            "lshk": ["ping3"]
        },
        {
            "chinese": "cakes",
            "roman": ["yam"],
            "yale": ["yam1"],
            "lshk": ["jam1"]
        }
    ],
    "synonyms": ["663ddf614f79af2b81fffaf9"] 
}