### READ
GET http://localhost:3000/vocabulary/663fec80a48c6a1dfd66f88c HTTP/1.1

### READ 
GET http://localhost:3000/vocabulary/yale/ping1 HTTP/1.1

### READ 
GET http://localhost:3000/vocabulary/roman/gei HTTP/1.1

### READ 
GET http://localhost:3000/vocabulary/lshk/jam1 HTTP/1.1

### CREATE
POST http://localhost:3000/vocabulary HTTP/1.1 
Content-Type: application/json

{
    "englishWord": "Romanisation",
    "englishDescription": "Newly Added Description",
    "characters": [
        {
            "chinese": "拼",
            "roman": ["ping"],
            "yale": ["ping1", "ping3"],
            "lshk": ["ping3"]
        },
        {
            "chinese": "音",
            "roman": ["yam"],
            "yale": ["yam1"],
            "lshk": ["jam1"]
        }
    ],
    "synonyms": [] 
}

### UPDATE
PUT http://localhost:3000/vocabulary/663fec80a48c6a1dfd66f88c
Content-Type: application/json

{
    "englishWord": "Updated PUT Romanisation",
    "englishDescription": "Updated Description",
    "characters": [
        {
            "chinese": "拼",
            "roman": ["ping"],
            "yale": ["ping1", "ping3"],
            "lshk": ["ping3"]
        },
        {
            "chinese": "拼",
            "roman": ["yam"],
            "yale": ["yam1"],
            "lshk": ["jam1"]
        }
    ],
    "synonyms": [] 
}
### DELETE 
DELETE http://localhost:3000/vocabulary/663fc70043f306f27d781eee

### Character lookup
GET http://localhost:3000/character/督


聖餐
耶穌基督